[workspace]
members = [
    "crates/pine-lexer",
    "crates/pine-ast",
    "crates/pine-parser",
    "crates/pine-interpreter",
]
resolver = "2"

[workspace.dependencies]
pine-lexer = { path = "crates/pine-lexer" }
pine-parser = { path = "crates/pine-parser" }
pine-ast = { path = "crates/pine-ast" }
eyre = "0.6"
thiserror = "2.0"
clap = { version = "4.5", features = ["derive"] }
